export const paths = {
  login: (): string => '/login',
  logout: (): string => '/logout',
  signup: (): string => '/signup',
  reset: (): string => '/reset',
  restore: (): string => '/restore',
  changed: (): string => '/changed',
  sended: (): string => '/sended',
  home: (): string => '/home',
  main: (): string => `${paths.home()}/main`,
  history_1: (): string => `${paths.main()}/history/:option`,
  import: (): string => `${paths.home()}/import`,
  export: (): string => `${paths.home()}/export`,
  referral: (): string => `${paths.home()}/referral`,
  help: (): string => `${paths.home()}/help`,
  control: (): string => `/control`,
  profile: (): string => `${paths.home()}/profile`,
  privacy: (): string => `/privacy`,
  test: (): string => '/test',
  error: (): string => '/error',
  //**** ADMIN PATHS ****/
  dashboard: (): string => `/dashboard`,
  actions: (): string => `${paths.dashboard()}/actions`,
  admins: (): string => `${paths.dashboard()}/admins`,
  management: (): string => `${paths.dashboard()}/management`,
  statistic: (): string => `${paths.dashboard()}/statistic`,
}
