import 'features/profile/model/init'
import 'features/main/model/init'
import 'features/statistic/user/model/init'
import 'features/referral/model/init'
import 'features/import/model/init'
import 'features/export/model/init'
import 'features/home/model/init'
import 'entities/common/model/toast/model'

import 'processes/auth/init'
